##############################################################################bl
# MIT License
#
# Copyright (c) 2021 - 2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
##############################################################################el

import csv
from dataclasses import dataclass
from pathlib import Path

from utils.logger import console_debug
from utils import file_io, parser, schema

################################################
# Global vars
################################################

IMGNAME = "empirRoof"

XMIN = 0.01
XMAX = 1000

FONT_SIZE = 16
FONT_COLOR = "black"
FONT_WEIGHT = "bold"

# SUPPORTED_DATATYPES table is based on datatype support in rocm-amdgpu-bench repository
# Indicates which datatypes per gpu arch can be generated by the roofline binary
SUPPORTED_DATATYPES = {
    "gfx90a": [
        "FP16",
        "BF16",
        "FP32",
        "FP64",
        "I8",
        "I32",
        "I64",
    ],  # Unsupported: F4, F6, F8
    "gfx940": [
        "FP8",
        "FP16",
        "BF16",
        "FP32",
        "FP64",
        "I8",
        "I32",
        "I64",
    ],  # Unsupported: F4, F6
    "gfx941": [
        "FP8",
        "FP16",
        "BF16",
        "FP32",
        "FP64",
        "I8",
        "I32",
        "I64",
    ],  # Unsupported: F4, F6
    "gfx942": [
        "FP8",
        "FP16",
        "BF16",
        "FP32",
        "FP64",
        "I8",
        "I32",
        "I64",
    ],  # Unsupported: F4, F6
    "gfx950": [
        "FP4",
        "FP6",
        "FP8",
        "FP16",
        "BF16",
        "FP32",
        "FP64",
        "I8",
        "I32",
        "I64",
    ],  # Unsupported:
}

PEAK_OPS_DATATYPES = ["FP8", "FP16", "BF16", "FP32", "FP64", "I8", "I32", "I64"]
MFMA_DATATYPES = ["FP4", "FP6", "FP8", "FP16", "BF16", "FP32", "FP64", "I8"]

TOP_N = 10


################################################
# Helper funcs
################################################
@dataclass
class AI_Data:
    KernelName: str
    numCalls: float

    total_flops: float
    valu_flops: float
    mfma_flops_f6f4: float
    mfma_flops_f8: float
    mfma_flops_f16: float
    mfma_flops_bf16: float
    mfma_flops_f32: float
    mfma_flops_f64: float
    mfma_iops_i8: float
    lds_data: float
    L1cache_data: float
    L2cache_data: float
    hbm_data: float

    totalDuration: float
    avgDuration: float


def get_font():
    return {
        "size": FONT_SIZE,
        "color": FONT_COLOR,
        "weight": FONT_WEIGHT,
        "family": "serif",
    }


def get_color(catagory):
    if catagory == "ai_l1":
        return "green"
    elif catagory == "ai_l2":
        return "blue"
    elif catagory == "ai_hbm":
        return "red"
    else:
        raise RuntimeError("Invalid catagory passed to get_color()")


# -------------------------------------------------------------------------------------
#                           Plot BW at each cache level
# -------------------------------------------------------------------------------------
def calc_ceilings(roofline_parameters, dtype, benchmark_data):
    """Given benchmarking data, calculate ceilings (or peak performance) for empirical roofline"""
    # TODO: This is where filtering by memory level will need to occur for standalone
    graphPoints = {"hbm": [], "l2": [], "l1": [], "lds": [], "valu": [], "mfma": []}

    if roofline_parameters["mem_level"] == "ALL":
        cacheHierarchy = ["HBM", "L2", "L1", "LDS"]
    else:
        cacheHierarchy = roofline_parameters["mem_level"]

    x1 = y1 = x2 = y2 = -1
    x1_mfma = y1_mfma = x2_mfma = y2_mfma = -1

    ops_flops = "Ops" if (dtype[:1] == "I") else "Flops"

    if dtype in PEAK_OPS_DATATYPES:
        peakOps = float(
            benchmark_data[dtype + "{}".format(ops_flops)][
                roofline_parameters["device_id"]
            ]
        )
    for i in range(0, len(cacheHierarchy)):
        # Plot BW line
        console_debug("roofline", "Current cache level is %s" % cacheHierarchy[i])
        curr_bw = cacheHierarchy[i] + "Bw"
        peakBw = float(benchmark_data[curr_bw][roofline_parameters["device_id"]])

        x1 = float(XMIN)
        y1 = float(XMIN) * peakBw

        if dtype in PEAK_OPS_DATATYPES:
            x2 = peakOps / peakBw
            y2 = peakOps

            # Plot MFMA lines (NOTE: Assuming MI200 soc)
            x1_mfma = peakOps / peakBw
            y1_mfma = peakOps

        if dtype in MFMA_DATATYPES:
            target_precision = (dtype) if (dtype[:1] == "I") else ("F" + dtype[2:])

            peakMFMA = float(
                benchmark_data["MFMA{}{}".format(target_precision, ops_flops)][
                    roofline_parameters["device_id"]
                ]
            )
            x2_mfma = peakMFMA / peakBw
            y2_mfma = peakMFMA

        # Check which peak is higher for formatting bandwidth lines
        if y2_mfma > y1_mfma:  # peakMFMA
            peakX = x2_mfma
            peakY = y2_mfma
        else:  # peakVALU
            peakX = x1_mfma
            peakY = y1_mfma

        # These are the points to use:
        console_debug("roofline", "coordinate points:")
        console_debug("x = [{}, {}]".format(x1, peakX))
        console_debug("y = [{}, {}]".format(y1, peakY))

        graphPoints[cacheHierarchy[i].lower()].append([x1, peakX])
        graphPoints[cacheHierarchy[i].lower()].append([y1, peakY])
        graphPoints[cacheHierarchy[i].lower()].append(peakBw)

    # -------------------------------------------------------------------------------------
    #                                     Plot computing roof
    # -------------------------------------------------------------------------------------
    if dtype in PEAK_OPS_DATATYPES:
        # Plot FMA roof
        x0 = XMAX
        if x2 < x0:
            x0 = x2

        console_debug("FMA ROOF [{}, {}], [{},{}]".format(x0, XMAX, peakOps, peakOps))
        graphPoints["valu"].append([x0, XMAX])
        graphPoints["valu"].append([peakOps, peakOps])
        graphPoints["valu"].append(peakOps)

    # Plot MFMA roof
    if dtype in MFMA_DATATYPES:  # assert that mfma has been assigned
        x0_mfma = XMAX
        if x2_mfma < x0_mfma:
            x0_mfma = x2_mfma

        console_debug(
            "MFMA ROOF [{}, {}], [{},{}]".format(x0_mfma, XMAX, peakMFMA, peakMFMA)
        )
        graphPoints["mfma"].append([x0_mfma, XMAX])
        graphPoints["mfma"].append([peakMFMA, peakMFMA])
        graphPoints["mfma"].append(peakMFMA)

    return graphPoints


# -------------------------------------------------------------------------------------
#                              Overlay application performance
# -------------------------------------------------------------------------------------
# Calculate relevant metrics for ai calculation
# def calc_ai(mspec, sort_type, ret_df, config_dir):
#     """
#     Calculates roofline data by invoking the generic parser engine and then
#     re-packaging the results into the legacy AI_Data format for backward
#     compatibility with the rest of this script.
#     """
#     print(config_dir)
#     roofline_yaml_path = Path(config_dir) / mspec.gpu_arch / "0400_roofline_info.yaml"
#     if not roofline_yaml_path.exists():
#         console_error(f"Roofline configuration for {mspec.gpu_arch} not found.")
#         return [] # Return an empty list, matching the old function's failure behavior.

#     # Step 2: Invoke the parser engine.
#     # This single call replaces all the manual calculation loops from the old function.
#     # It passes the raw PMC data and the path to our new YAML.
#     # The parser returns a pandas DataFrame with a column for every metric in the YAML.
#     # Note: The 'workload' object must be constructed here or passed in.
#     # This example assumes a helper function can build it.
#     workload = build_workload_object(mspec, ret_df, roofline_yaml_path)
#     results_df = run_parser_for_workload(workload)
    
#     # `results_df` is now a DataFrame where each row is a kernel dispatch, and columns
#     # are 'hbm_data', 'mfma_flops_f64', 'Kernel_Name', 'End_Timestamp', etc.

#     # Step 3: Re-package the DataFrame results into the old `myList` format.
#     # This is the crucial step for backward compatibility.
#     myList = []
#     # We assume the parser returns one row per dispatch. If kernel aggregation is needed,
#     # we must group the DataFrame by Kernel Name first.
#     if sort_type == "kernels":
#         # This groups by kernel and sums all numeric columns.
#         kernel_groups = results_df.groupby('Kernel_Name')
#         aggregated_results = kernel_groups.sum(numeric_only=True)
#         # We also need to get the first value for non-numeric or metadata columns.
#         aggregated_results['Kernel_Name'] = kernel_groups['Kernel_Name'].first()
#         aggregated_results['num_calls'] = kernel_groups.size()
#         results_to_process = aggregated_results
#     else: # sort_type == "dispatches"
#         results_to_process = results_df

#     for _, row in results_to_process.iterrows():
#         # Create an AI_Data object by mapping DataFrame columns to the dataclass fields.
#         # The .get(column, 0.0) provides a default value if a metric wasn't calculated.
#         ai_instance = AI_Data(
#             KernelName=row.get('Kernel_Name', 'Unknown'),
#             numCalls=row.get('num_calls', 1),
            
#             total_flops=row.get('total_flops', 0.0),
#             valu_flops=row.get('valu_flops', 0.0),
#             mfma_flops_f6f4=row.get('mfma_flops_f6f4', 0.0),
#             mfma_flops_f8=row.get('mfma_flops_f8', 0.0),
#             mfma_flops_f16=row.get('mfma_flops_f16', 0.0),
#             mfma_flops_bf16=row.get('mfma_flops_bf16', 0.0),
#             mfma_flops_f32=row.get('mfma_flops_f32', 0.0),
#             mfma_flops_f64=row.get('mfma_flops_f64', 0.0),
#             mfma_iops_i8=row.get('mfma_iops_i8', 0.0),
#             lds_data=row.get('lds_data', 0.0),
#             L1cache_data=row.get('L1cache_data', 0.0),
#             L2cache_data=row.get('L2cache_data', 0.0),
#             hbm_data=row.get('hbm_data', 0.0),
            
#             # Calculate total and average duration from the raw timestamps.
#             totalDuration=(row.get('End_Timestamp', 0) - row.get('Start_Timestamp', 0)),
#             avgDuration=(row.get('End_Timestamp', 0) - row.get('Start_Timestamp', 0)) / row.get('num_calls', 1)
#         )
#         myList.append(ai_instance)
        
#     # Step 4: Return the data in the exact same format as the old function.
#     # The rest of roofline_calc.py will receive this list and function exactly as before.
#     myList.sort(key=lambda x: x.totalDuration, reverse=True)
    
#     # The final processing loop from the old function can remain, as it operates on `myList`.
#     intensities = {"ai_l1": [], "ai_l2": [], "ai_hbm": []}
#     curr_perf = []
#     kernelNames = []
#     i = 0
#     # Create list of top 5 intensities
#     while i < TOP_N and i != len(myList):
#         if myList[i].total_flops == 0:
#             console_debug(
#                 "No flops counted for {}, arithmetic intensities will not display on plots.".format(
#                     myList[i].KernelName
#                 )
#             )

#         kernelNames.append(myList[i].KernelName)
#         (
#             intensities["ai_l1"].append(myList[i].total_flops / myList[i].L1cache_data)
#             if myList[i].L1cache_data
#             else intensities["ai_l1"].append(0)
#         )
#         # print("cur_ai_L1", myList[i].total_flops/myList[i].L1cache_data) if myList[i].L1cache_data else print("null")
#         # print()
#         (
#             intensities["ai_l2"].append(myList[i].total_flops / myList[i].L2cache_data)
#             if myList[i].L2cache_data
#             else intensities["ai_l2"].append(0)
#         )
#         # print("cur_ai_L2", myList[i].total_flops/myList[i].L2cache_data) if myList[i].L2cache_data else print("null")
#         # print()
#         (
#             intensities["ai_hbm"].append(myList[i].total_flops / myList[i].hbm_data)
#             if myList[i].hbm_data
#             else intensities["ai_hbm"].append(0)
#         )
#         # print("cur_ai_hbm", myList[i].total_flops/myList[i].hbm_data) if myList[i].hbm_data else print("null")
#         # print()
#         (
#             curr_perf.append(myList[i].total_flops / myList[i].avgDuration)
#             if myList[i].avgDuration
#             else curr_perf.append(0)
#         )
#         # print("cur_perf", myList[i].total_flops/myList[i].avgDuration) if myList[i].avgDuration else print("null")

#         i += 1

#     intensityPoints = {"ai_l1": [], "ai_l2": [], "ai_hbm": []}

#     for i in intensities:
#         values = intensities[i]

#         color = get_color(i)
#         x = []
#         y = []
#         for entryIndx in range(0, len(values)):
#             x.append(values[entryIndx])
#             y.append(curr_perf[entryIndx])

#         intensityPoints[i].append(x)
#         intensityPoints[i].append(y)

#     # Add an entry for kernel names
#     intensityPoints["kernelNames"] = kernelNames

#     return intensityPoints


def constuct_roof(roofline_parameters, dtype):
    workload_dir = roofline_parameters.get("workload_dir")
    if isinstance(workload_dir, list):
        base_dir = (
            workload_dir[0][0]
            if isinstance(workload_dir[0], (list, tuple))
            else workload_dir[0]
        )
    else:
        base_dir = workload_dir

    benchmark_results = str(Path(base_dir) / "roofline.csv")

    # -----------------------------------------------------
    # Initialize roofline data dictionary from roofline.csv
    # -----------------------------------------------------
    benchmark_data = (
        {}
    )  # TODO: consider changing this to an ordered dict for consistency over py versions
    headers = []
    try:
        with open(benchmark_results, "r") as csvfile:
            csvReader = csv.reader(csvfile, delimiter=",")
            rowCount = 0
            for row in csvReader:
                row.pop(0)  # remove devID
                if rowCount == 0:
                    headers = row
                    for i in headers:
                        benchmark_data[i] = []
                else:
                    for i, key in enumerate(headers):
                        benchmark_data[key].append(row[i])

                rowCount += 1
        csvfile.close()
    except:
        graphPoints = {
            "hbm": [None, None, None],
            "l2": [None, None, None],
            "l1": [None, None, None],
            "lds": [None, None, None],
            "valu": [None, None, None],
            "mfma": [None, None, None],
        }
        return graphPoints

    # ------------------
    #  Generate Roofline
    # ------------------
    results = calc_ceilings(roofline_parameters, dtype, benchmark_data)

    return results